polychromatic-tray-applet(1)

# NAME

Polychromatic - Graphical front-end for the OpenRazer daemon.

# SYNOPSIS

*polychromatic-tray-applet*

# DESCRIPTION

A graphical front-end for managing Razer peripherals powered by the OpenRazer
daemon. This includes changing lighting effects, changing brightness and
creating key light profiles for applications/games.

# OPTIONS

*-h*, *--help*
	Shows the help information.
*-v*, *--verbose*
	Outputs more details about the operation of the application.
