.TH polychromatic-tray-applet 1
.SH NAME
Polychromatic \- Graphical front-end for the OpenRazer daemon.
.SH SYNOPSIS
.B polychromatic-tray-applet
.SH DESCRIPTION
A graphical front-end for managing Razer peripherals powered by the OpenRazer daemon. This includes changing lighting effects, changing brightness and creating key light profiles for applications/games.
