.TH polychromatic-controller 1
.SH NAME
Polychromatic \- Graphical front-end for the OpenRazer daemon.
.SH SYNOPSIS
.B polychromatic-controller [\fB\-h\fR \fI--help\fR] [\fB\-v\fR \fI--verbose\fR]  [\fB\-vv\fR \fI--debug\fR]
.SH DESCRIPTION
A graphical front-end for managing Razer peripherals powered by the OpenRazer daemon. This includes changing lighting effects, changing brightness and creating key light profiles for applications/games.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Shows the help information.
.TP
.BR \-v ", " \-\-verbose
Outputs more details about the operation of the application.
.TP
.BR \-vv ", " \-\-debug
Same as --verbose, but also outputs details of the flow of data being passed between WebKit2 and Python.
