#!/bin/bash
#
# Starts Polychromatic Controller and performs essential tasks like
# compiling the styles and locales.
#
# The save data is isolated into a directory named "dev".
#
# Parameters: Uses --verbose by default, as well as any others passed when
# executing this script.
#
params=$*

cd "$(dirname "$0")"

function abort_on_error() {
    if [ $1 != 0 ]; then exit 1; fi
}

# Compile SASS files
./scripts/build-styles.sh
abort_on_error $?

# Compile locales
./scripts/build-locales.sh
abort_on_error $?

# Isolate configuration
export POLYCHROMATIC_DEV_CFG=true

# Start!
exec ./polychromatic-controller --verbose $params
